# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d4c13c954377ad2960481fdb3f31005c0ca71548fe93d69620f837b7610ebfd473604c3dba9c93dd32744c922d232da77f79d17a30ee941b69e6ca3d783943

test:
  secret_key_base: 3ce1dea67d0e28f7c748a1dbf27fac70a003a17e08f6af271ed7ecc736a29c00dc7c228ce470ad2ed044eaddd248056e881adde5621f579dc92391b2277bb839

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
